homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Berlin

  customize: !include customize.yaml

lovelace:
  mode: yaml

frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

system_health:

updater:
  include_used_components: true # Allows Home Assistant developers to focus on popular components.

#logger:
#  default: info

# Discover some devices automatically
discovery:

# Track the sun
sun:

# Fritzbox
fritzbox:
  devices:
    - host: !secret fritz_ip
      username: !secret fritz_user
      password: !secret fritz_passwd

# MQTT
mqtt:
  username: !secret mqtt_user
  password: !secret mqtt_passwd
  port: !secret mqtt_port

# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_my_chat_id

sensor: !include sensors.yaml
group: !include_dir_merge_named groups
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
switch: !include switch.yaml
logbook: !include logbook.yaml
recorder: !include recorder.yaml
notify: !include notify.yaml
history: !include history.yaml
