version: '2'
services:
    deconz:
        container_name: deconz
        env_file: .env
        restart: always
        network_mode: 'host'
        environment:
            - DECONZ_WEB_PORT=${DECONZ_WEB_PORT}
            - DECONZ_WS_PORT=${DECONZ_WS_PORT}
        volumes:
            - '${INSTALL_FOLDER}/deconz:/opt/deCONZ'
        devices:
            - /dev/ttyAMA0
        image: 'deconzcommunity/deconz:2.13.03'
    home-assistant:
        container_name: home-assistant
        env_file: .env
        restart: always
        network_mode: 'host'
        depends_on:
            - "deconz"
            - "mosquito"
        volumes:
            - '${INSTALL_FOLDER}/homeassistant:/config'
            - '/etc/localtime:/etc/localtime:ro'
        image: 'homeassistant/raspberrypi3-homeassistant:2022.8.7'
    pihole:
        container_name: pihole
        env_file: .env
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '67:67/udp'
            - '80:80'
            - '443:443'
        volumes:
            - '${INSTALL_FOLDER}/pihole/pihole/:/etc/pihole/'
            - '${INSTALL_FOLDER}/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
        environment:
            - 'ServerIP=${IP}'
            - 'WEBPASSWORD=${WEBPASSWORD}'
            - 'TZ=Europe/Berlin'
        restart: always
        dns:
            - 127.0.0.1
            - 1.1.1.1
        image: 'pihole/pihole:2022.04.1'
    mosquito:
        container_name: mosquito
        env_file: .env
        network_mode: 'host'
        volumes:
            - '${INSTALL_FOLDER}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf'
            - '${INSTALL_FOLDER}/mosquitto/mosquitto_passwd:/etc/mosquitto/passwd'
        restart: always
        image: 'eclipse-mosquitto:2.0.14'
