
# Time
- platform: time_date
  display_options:
    - 'time'

# System Monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: load_15m

# Raspberry CPU Temperature
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) }}'

# Pihole
- platform: pi_hole
  name: Pihole
  monitored_conditions:
    - dns_queries_today
    - ads_blocked_today
    - ads_percentage_today
    - queries_cached
    - unique_clients
    - domains_being_blocked

# Google Maps
- platform: google_travel_time
  name: Gmaps Home2MeetingPoint
  api_key: !secret gmaps_api_key
  origin: !secret gmaps_home
  destination: !secret gmaps_fgm
  scan_interval: 03:00:00
  options:
    mode: driving
    departure_time: now

- platform: google_travel_time
  name: Gmaps MeetingPoint2Work
  api_key: !secret gmaps_api_key
  origin: !secret gmaps_fgm
  destination: !secret gmaps_work
  scan_interval: 03:00:00
  options:
    mode: driving
    departure_time: now

- platform: google_travel_time
  name: Gmaps Work2MeetingPoint
  api_key: !secret gmaps_api_key
  origin: !secret gmaps_work
  destination: !secret gmaps_fgm
  scan_interval: 03:00:00
  options:
    mode: driving
    departure_time: now

- platform: google_travel_time
  name: Gmaps MeetingPoint2Home
  api_key: !secret gmaps_api_key
  origin: !secret gmaps_fgm
  destination: !secret gmaps_home
  scan_interval: 03:00:00
  options:
    mode: driving
    departure_time: now
