
title: Home

resources:
  - url: /local/mini-graph-card-bundle.js?v=0.10.0
    type: module
  - url: /local/monster-card.js?v=1
    type: js

views:
  - title: Dashboard
    icon: mdi:home
    cards:
      - type: entities
        title: Personen
        show_header_toggle: false
        entities:
          - device_tracker.husband
          - device_tracker.wife_a2
      - type: entities
        title: Alle Steckdosen
        show_header_toggle: false
        entities:
          - switch.sonoff2

      - type: custom:mini-graph-card
        entities:
        - sensor.humidor_pressure
        height: 100
        line_width: 4
        font_size: 75
        labels: true
        line_color: '#03a9f4'
      - type: custom:mini-graph-card
        entities:
        - sensor.humidor_humidity
        height: 100
        line_width: 4
        font_size: 75
        labels: true
        line_color: '#03a9f4'

  - title: Graphs
    icon: mdi:chart-line-variant
    cards:
      - type: history-graph
        title: Temperature
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - sensor.humidor_humidity
          - sensor.humidor_pressure
          - sensor.humidor_temperature

  - title: Admin
    icon: mdi:account-alert
    cards:
      - type: entities
        title: Personen
        show_header_toggle: false
        entities:
          - device_tracker.husband
          - device_tracker.wife_a2
      - type: entities
        title: "Alle Geräte"
        show_header_toggle: false
        entities:
          - device_tracker.wife_a2
          - device_tracker.husband
      - title: All_Automations
        type: "custom:monster-card"
        card:
          type: entities
          title: All Automations
        filter:
          include:
            - entity_id: "automation.*"
          exclude:
            - attributes:
                hidden: true
      - title: All_Scripts
        type: "custom:monster-card"
        show_header_toggle: false
        icon: mdi:home-automation
        card:
          type: entities
          title: All Scripts
        filter:
          include:
            - entity_id: "script.*"
      - type: entities
        title: Alle Steckdosen
        show_header_toggle: false
        entities:
          - switch.sonoff2
      - type: entities
        title: Anderes
        show_header_toggle: false
        entities:
          - sun.sun
          - sensor.time
          - sensor.daylight
      - type: entities
        title: Sensoren
        show_header_toggle: false
        entities:
          - binary_sensor.water
          - sensor.humidor_humidity
          - sensor.humidor_pressure
          - sensor.humidor_temperature

  - title: Pi
    cards:
      - type: entities
        title: Raspberry Pi
        show_header_toggle: false
        entities:
          - sensor.processor_use
          - sensor.cpu_temperature
          - sensor.disk_use_percent
          - sensor.memory_use_percent
          - sensor.load_15m
          - sensor.last_boot
      - type: entities
        title: DNS AdBlock!
        show_header_toggle: false
        entities:
          - sensor.pi_hole_dns_queries_today
          - sensor.pi_hole_ads_blocked_today
          - sensor.pi_hole_ads_percentage_blocked_today
          - sensor.pi_hole_dns_queries_cached
          - sensor.pi_hole_dns_unique_clients
          - sensor.pi_hole_domains_blocked
