
# Time
- platform: time_date
  display_options:
    - 'time'

# System Monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: load_15m

# Raspberry CPU Temperature
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) }}'

# Medtronic Minimed 640G
- platform: template
  sensors:
    minimed_bgl:
      friendly_name: 'Sensor BGL'
      value_template: ""
      unit_of_measurement: 'mg/dl'
      icon_template: mdi:home-heart
    minimed_trend:
      friendly_name: 'Trend'
      value_template: ""
      icon_template: mdi:trending-up
    minimed_current_basal_rate:
      friendly_name: 'Current basal rate'
      value_template: ""
    minimed_temp_basal_rate:
      friendly_name: 'Temporary basal rate'
      value_template: ""
    minimed_temp_basal_rate_percentage:
      friendly_name: 'Temporary basal rate percentage'
      value_template: ""
    minimed_active_insulin:
      friendly_name: 'Active insulin'
      value_template: ""
      unit_of_measurement: 'U'
      icon_template: mdi:trending-up
    minimed_pump_battery_level:
      friendly_name: 'Pump battery level'
      value_template: ""
      unit_of_measurement: '%'
      icon_template: mdi:battery
    minimed_insulin_units_remaining:
      friendly_name: 'Insulin units remaining'
      value_template: ""
      unit_of_measurement: 'U'
      icon_template: mdi:history
    minimed_message:
      friendly_name: 'Pump message'
      value_template: ""
      icon_template: mdi:message
    minimed_update_timestamp:
      friendly_name: 'Latest Update'
      value_template: ""
      icon_template: mdi:home-heart
    minimed_status:
      friendly_name: 'Connection Status'
      value_template: ""
