- alias: 'Heizdecke an'
  initial_state: 'off'
  trigger:
  - at: !secret hd_on
    platform: time
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.wife_A2
      state: home
    - condition: state
      entity_id: binary_sensor.workday_tomorrow
      state: 'on'
  action:
  - alias: ''
    data:
      entity_id: switch.sonoff1
    service: switch.turn_on


- alias: 'Heizdecke aus'
  initial_state: 'off'
  trigger:
  - at: !secret hd_off
    platform: time
  condition:
  - condition: state
    entity_id: switch.sonoff1
    state: 'on'
  action:
  - alias: ''
    data:
      entity_id: switch.sonoff1
    service: switch.turn_off


- alias: 'Heizdecke, max Time aus'
  initial_state: 'off'
  trigger:
  - entity_id: switch.sonoff1
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:40:00
  - alias: ''
    entity_id: switch.sonoff1
    service: switch.turn_off


- alias: 'Heizdecke notify'
  initial_state: 'off'
  trigger:
  - platform: state
    entity_id: switch.sonoff1
  action:
  - data_template:
      message: 'Heizdecke {{ trigger.to_state.state }}'
      title: '*Heizdecke*'
    service: notify.notify_me
