- alias: 'Weekday, Dining room lights on'
  initial_state: 'off'
  trigger:
  - at: !secret dining_room_on_time
    platform: time
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.light_1


- alias: 'No one at home. All off'
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: group.residents
    from: home
    to: not_home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
  - service: light.turn_off
    entity_id: group.all_lights
  - service: switch.turn_off
    entity_id: switch.sonoff2


- alias: 'Coming Home'
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: group.residents
    from: not_home
    to: home
  action:
  - service: switch.turn_on
    entity_id: switch.sonoff2


- alias: 'Dining Room, mornings light colour cold'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: light.light_1
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '00:00:00'
    before: '09:00:00'
  action:
  - service: light.turn_on
    data:
      entity_id: light.light_1
      color_temp: 250


- alias: 'Dining Room, evening light colour warm'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: light.light_1
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '09:00:01'
    before: '23:00:00'
  action:
  - service: light.turn_on
    data:
      entity_id: light.light_1
      color_temp: 390
