- alias: 'Aquarium Wassererkennung'
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.water_6
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Es wurde am Aquarium Wasser erkannt!
      title: '*Wasser erkannt*'
    service: notify.notify_me


- alias: 'Humidor Luftfeuchte notify'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity_6
    above: 72
  action:
  - data_template:
      message: 'Luftfeuchte liegt bei {{ states.sensor.humidity_6.state }} %!'
      title: '*Humidor Luftfeuchte zu hoch*'
    service: notify.notify_me


- alias: 'Update Available Notifications'
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.notify_me
    data_template:
      message: 'Update for Home Assistant is available. v{{ states.updater.updater.state }}'
      title: '*Update verfügbar*'
