- alias: 'No one at home. All off'
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: group.residents
    from: home
    to: not_home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
  - service: switch.turn_off
    entity_id: switch.sonoff2


- alias: 'Coming Home'
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: group.residents
    from: not_home
    to: home
  action:
  - service: switch.turn_on
    entity_id: switch.sonoff2