- alias: 'Medtronic Message'
  initial_state: 'on'
  trigger:
  - entity_id: sensor.minimed_message
    not_to: ''
    platform: state
  action:
  - data_template:
      message: '{{ states.sensor.minimed_message.state }}'
      title: '*Medtronic Alarm*'
    service: notify.notify_both
  - condition: time
    after: '21:00:00'
    before: '07:30:00'
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.medtronic_alarm_delay_switch 

- alias: Auto Off Medtronic Switch
  initial_state: 'off'
  trigger:
  - platform: state
    entity_id: input_boolean.medtronic_switch
    to: 'on'
    for: '03:00:00'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.medtronic_switch

- alias: 'BGL too low warning'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.minimed_ui_bgl
    below: 80
  action:
  - data_template:
      message: 'BGL at {{ states.sensor.minimed_ui_bgl.state }}!'
      title: '*BGL low*'
    service: notify.notify_both

- alias: 'BGL below 70'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.minimed_ui_bgl
    below: 70
  action:
  - data_template:
      message: 'BGL at {{ states.sensor.minimed_ui_bgl.state }}!'
      title: '*BGL below 70*'
    service: notify.notify_both
  - condition: time
    after: '21:00:00'
    before: '07:30:00'
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.medtronic_alarm_delay_switch 

- alias: 'BGL above 250'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.minimed_ui_bgl
    above: 250
  action:
  - data_template:
      message: 'BGL at {{ states.sensor.minimed_ui_bgl.state }}!'
      title: '*BGL above 250*'
    service: notify.notify_both
  - condition: time
    after: '21:00:00'
    before: '07:30:00'
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.medtronic_alarm_delay_switch 

- trigger:
  - platform: state
    entity_id: sensor.minimed_ui_bgl
  alias: 'BGL too low prediction'
  initial_state: 'on'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.minimed_ui_bgl
        below: 90
      - condition: numeric_state
        entity_id: sensor.minimed_ui_active_insulin
        above: 0.1
      - condition: template
        value_template: '{{ trigger.from_state.state|int - trigger.to_state.state|int > 3 }}'
  action:
  - data_template:
      message: 'BGL at {{ states.sensor.minimed_ui_bgl.state }}!'
      title: '*BGL low prediction*'
    service: notify.notify_both

- alias: Watchdog
  initial_state: 'on'
  trigger:
    platform: time_pattern
    minutes: "/5"
  action:
    - service: script.watchdog
      data:
        entity_id: sensor.minimed_update_timestamp
        time: 900

- alias: 'Activate shelly plug after delay'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.medtronic_alarm_delay_switch
    to: 'on'
    for:
      seconds: 30
  action:
  - service: switch.turn_on
    entity_id: switch.shelly1

- alias: 'Acknowledge medtronic alarm'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_button.medtronic_alarm_acknowledge
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.medtronic_alarm_delay_switch
  - service: switch.turn_off
    entity_id: switch.shelly1
