- alias: 'Medtronic Message'
  initial_state: 'on'
  trigger:
  - entity_id: sensor.minimed_message
    not_to: ''
    platform: state
  action:
  - data_template:
      message: '{{ states.sensor.minimed_message.state }}'
      title: '*Medtronic Alarm*'
    service: notify.notify_both

- alias: Auto Off Medtronic Switch
  initial_state: 'off'
  trigger:
  - platform: state
    entity_id: input_boolean.medtronic_switch
    to: 'on'
    for: '03:00:00'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.medtronic_switch

- alias: 'BGL too low warning'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.minimed_ui_bgl
    below: 80
  action:
  - data_template:
      message: 'BGL at {{ states.sensor.minimed_ui_bgl.state }}!'
      title: '*BGL low*'
    service: notify.notify_both
