- alias: 'Aquarium Wassererkennung'
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.water
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Es wurde am Aquarium Wasser erkannt!
      title: '*Wasser erkannt*'
    service: notify.notify_me


- alias: 'Humidor humidity high notify'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.humidor_humidity
    above: 72
  action:
  - data_template:
      message: 'Luftfeuchte liegt bei {{ states.sensor.humidor_humidity.state }} %!'
      title: '*Humidor humidity high*'
    service: notify.notify_me


- alias: 'Humidor humidity low notify'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.humidor_humidity
    below: 70
  action:
  - data_template:
      message: 'Luftfeuchte liegt bei {{ states.sensor.humidor_humidity.state }} %!'
      title: '*Humidor humidity low*'
    service: notify.notify_me


- alias: 'Medtronic Message'
  initial_state: 'on'
  trigger:
  - entity_id: sensor.minimed_message
    from: ''
    platform: state
  action:
  - data_template:
      message: '{{ states.sensor.minimed_message.state }}'
      title: '*Medtronic Alarm*'
    service: notify.notify_me
