- alias: 'Night. Dark Theme'
  initial_state: 'on'
  trigger:
  - at: '22:00'
    platform: time
  condition: []
  action:
  - alias: ''
    data:
      name: midnight
    service: frontend.set_theme


- alias: 'Morning. Main Theme'
  initial_state: 'on'
  trigger:
  - at: '07:00'
    platform: time
  condition: []
  action:
  - alias: ''
    data:
      name: default
    service: frontend.set_theme
