- alias: 'Tradfri Remote 1 Control'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_fernbedienung
  action:
  - service_template: "{% if trigger.event.data.event == 1002 %}\n  script.toggle_light_kitchen_diningroom\n\
      {% elif trigger.event.data.event == 1003 %}\n  script.toggle_light_kitchen_diningroom\n\
      {% elif trigger.event.data.event == 4002 %}\n  script.toggle_light_diningroom\n\
      {% elif trigger.event.data.event == 4003 %}\n  script.toggle_light_diningroom\n\
      {% elif trigger.event.data.event == 5002 %}\n  script.toggle_light_kitchen\n\
      {% elif trigger.event.data.event == 5003 %}\n  script.toggle_light_kitchen\n\
      {% endif %}\n"
